
languageCode = "en-US"
defaultContentLanguage = "en"
theme = ["hugo-theme-relearn"]
uglyURLs = true
canonifyURLs = true # true -> all relative URLs would instead be canonicalized using baseURL
relativeURLs = true # true -> rewrite all relative URLs to be relative to the current content
enableGitInfo = true

[params]
  googleAnalytics = 'G-D0GB95LVDG'
  themeVariant = "custom"
  disableSearch = true
  disableLandingPageButton = true
  showVisitedLinks = true
  externalLinkTarget = "_blank"
  collapsibleMenu = true
