
# canonifyURLs = true # true -> all relative URLs would instead be canonicalized using baseURL
# relativeURLs = true # true -> rewrite all relative URLs to be relative to the current content

languageCode = "en-US"
defaultContentLanguage = "en"
theme = ["hugo-theme-relearn"]

uglyURLs = true

enableGitInfo = true

[params]
  editURL = "https://github.com/robinmordasiewicz/fortinet-forticnp-hugo-md/edit/main/"
  logoBannerText="FortiCNP"
  logoBannerSubText="Version 22.4a"
  author = "Robin Mordasiewicz"
  description = "Fortinet Cloud Native Protection Presentation"
  themeVariant = "fortinet"
  disableSearch = true
  disableLandingPageButton = true
  showVisitedLinks = true
  externalLinkTarget = "_blank"
  collapsibleMenu = true
