[comments]
  provider = "giscus"
  commentable = {page = true, post = true, docs = false, project = false, publication = true, talk = false}

  [comments.giscus]
    repo = "robinmordasiewicz/fortinet-hugo-theme"
    repo_id="R_kgDOJtwPUw"
    category = "Announcements"
    category_id="DIC_kwDOJtwPU84CXbqM"
    mapping = "pathname"
    label = "comment"
    theme = "light"
    reactions_enabled = 0
    strict = 0
    emit-metadata = 0
    input-position = "bottom"
    lang = "en"
    crossorigin = "anonymous"
