[comments]
  provider = "giscus"
  commentable = {page = true, post = true, docs = false, project = false, publication = true, talk = false}

  # Configuration of giscus
  [comments.giscus]
    repo = "robinmordasiewicz/fortinet-forticnp-hugo-md"
    repo_id = "R_kgDOJtuM1w"
    category = "General"
    category_id = "DIC_kwDOJtuM184CXPYd"
    mapping = "pathname"
    label = "comment"
    theme = "light"
    reactions_enabled = 0
    strict = 0
    emit-metadata = 0
    input-position = "bottom"
    lang = "en"
    crossorigin = "anonymous"

