name: content

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - "README.md"
    branches:
      - main
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  create_artifacts:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        repo: [fortinet-forticnp, fortinet-secure-cloud-blueprint]
    steps:
      - name: Checkout Hugo Template
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout Content
        uses: actions/checkout@v3
        with:
          path: content/${{ matrix.repo }}
          repository: robinmordasiewicz/${{ matrix.repo }}
          fetch-depth: 0
#      - name: Get all changed .ssml
#        id: ssml
#        uses: tj-actions/changed-files@v36
#        with:
#          path: ./content/${{ matrix.repo }}
#          separator: ","
#          files: |
#            **.ssml
#      - name: Get all changed .mov
#        id: mov
#        uses: tj-actions/changed-files@v36
#        with:
#          path: ./content/${{ matrix.repo }}
#          separator: ","
#          files: |
#            **.mov
